project:
  type: website
  output-dir: docs
  resources: files

website:
  title: "Dianne H. Cook"
  favicon: logo.png
  site-url: https://dicook.org
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Education
        href: education.qmd
      - text: Publications
        href: publications.qmd
      - text: Talks
        href: talks.qmd
      - text: Software
        href: software.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Students
        href: students.qmd
      - text: Blog
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/dicook/dicook-quarto      

body-footer: | 
  Copyright:  Dianne Cook, 2024

date-format: "D MMMM YYYY"

format:
  html:
    theme: 
      - pulse
      - custom.scss
    toc: true

